---
- name: POST to Tower API
  hosts: all
  tasks:
    - name: get details
      uri:
        url: https://18.216.19.92/api/v2/job_templates/24/  
        method: GET
    - name: invoke job
      uri:
        url: https://18.216.19.92/api/v2/job_templates/24/launch/
        method: POST
        user: admin
        password: ansible@123
        validate_certs: no
