---
- name: POST to Tower API
  hosts: webservers
  become: true
  tasks:
    - name: Invoke download Job job_templates
      uri:
        url: https://18.216.19.92/api/v2/job_templates/24/launch/
        method: POST
        user: admin
        password: ansible@123
        validate_certs: no
#        body: 
#        body_format: json
        status_code: 201
        validate_certs: no 
