---
- name: POST to Tower API
  hosts: all
  become: true
  tasks:
    - name: Invoke download Job job_templates
      uri:
        url: https://18.216.19.92:443/api/v2/job_templates/24/callback/
        clien_key: 674736fdbad4f6af6fb2f7875becf824
        method: POST
        user: admin
        password: ansible@123
        validate_certs: no
#        body: 
#        body_format: json
        status_code: 200
        validate_certs: no 
